on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.0
      - name: Build with Gradle
        run: gradle build --no-daemon
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: SybSafetyFirst Downloadable JAR
          path: 'build/libs/*-all.jar'
      - name: Create Dokka Documentation
        if: github.ref == 'refs/heads/main'
        run: gradle dokkaHtml --no-daemon
      - name: Publish Dokka Documentation
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/html
  deploy:
    name: Deploy documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4