on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.0
      - name: Build with Gradle
        run: gradle build --no-daemon
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: SybSafetyFirst Downloadable JAR
          path: 'build/libs/*-all.jar'