name: Publish Release

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.0
      - name: Build with Gradle
        run: gradle build -Pversion=${{ github.event.release.tag_name }} --no-daemon
      - name: Upload Release Assets
        run: |
          gh release upload ${{ github.event.release.tag_name }} build/libs/SybSafetyFirst-${{ github.event.release.tag_name }}-all.jar
          gh release upload ${{ github.event.release.tag_name }} build/libs/SybSafetyFirst-${{ github.event.release.tag_name }}-min.jar
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ vars.MODRINTH_PROJECT_ID }}
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            paper
            spigot
            bukkit
            purpur
          game-versions: |-
            1.21.x
            1.20.x
            1.19.x
            1.18.x
            1.17.x
            1.16.x
          files: build/libs/SybSafetyFirst-${{ github.event.release.tag_name }}-min.jar